### ISSUE TITLE
 Cannot install in R.

### ISSUE THREAD

**Issue by RZRuiZhang** [fenguoerbian/RSAVS#1]
Cannot install in R.
<img width="941" alt="Screen Shot 2023-02-16 at 16 51 26" src="https://user-images.githubusercontent.com/115213548/219315119-8675d608-397d-4d2e-be30-1b258fbf1ec5.png">

**Comment by fenguoerbian** [comment]
According to error message, `fpc` package is missing,  also looks like other dependent packages are not successfully installed.
You should check and make sure those packages are installed.
