### ISSUE TITLE
R program 

### ISSUE THREAD

**Issue by RZRuiZhang** [fenguoerbian/RSAVS#2]
Hi,
It is not a technology issue. I would like to know about using this code to edit my own code. However, as a novice, the whole R package things confuse me. Could the author give some suggestions, if I want to code my own RSAVS_LargeN() function, so that I can edit it based on the pre_define_functions.r program. Do I need to load some other libraries or functions?

I would really appreciate it if you could help me.

Best,
Rui

**Comment by fenguoerbian** [comment]
You can write your own function, in which utilizes the functions defined in this package. You can use `RSAVS::<function_name>` or `RSAVS:::<function_name>` to access the functions in this package, depending on whether the `<function_name>` is already exported in namespace, so `::` or `:::`.

In this way the function you write in assigned in your R session's global environment. Or if you want you can fork this project, edit that `RSAVS_LargeN` as you need, rebuild and reinstall your own version of `RSAVS`.
