### ISSUE TITLE
Cannot install in R

### ISSUE THREAD

**Issue by lyh199800** [fenguoerbian/RSAVS#3]
Cannot install in R

* installing *source* package ‘RSAVS’ ...
** using staged installation
** libs
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppEigen/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c RSAVS_ADMM_LargeN.cpp -o RSAVS_ADMM_LargeN.o
RSAVS_ADMM_LargeN.cpp:5:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [RSAVS_ADMM_LargeN.o] Error 1
ERROR: compilation failed for package ‘RSAVS’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RSAVS’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/g9/z6m6z73s4cv7g0pn_vc1314c0000gn/T//Rtmpylcxml/file22254845ad59/RSAVS_0.1.3.tar.gz’ had non-zero exit status

**Comment by fenguoerbian** [comment]
looks like you're using clang and arm archtecture. I'm guessing you're using a Mac. Please refer to R manual about how to enable OpenMP support on Mac and clang.

**Comment by lyh199800** [comment]
OK I see. thank you so much! have a nice day!

--------------原始邮件--------------
发件人："Chao&nbsp;Cheng ***@***.***&gt;;
发送时间：2024年5月8日(星期三) 下午5:37
收件人："fenguoerbian/RSAVS" ***@***.***&gt;;
抄送："lyh199800 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [fenguoerbian/RSAVS] Cannot install in R (Issue #3)
-----------------------------------

 

 
looks like you're using clang and arm archtecture. I'm guessing you're using a Mac. Please refer to R manual about how to enable OpenMP support on Mac and clang.

**Comment by lyh199800** [comment]
hi, even after switching to a Windows computer, I still can't install it. Could you please help me check what the problem might be? Thank you very much!

> devtools::install_github("fenguoerbian/RSAVS")
Downloading GitHub repo fenguoerbian/RSAVS@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\liuyahang\AppData\Local\Temp\RtmpIhEufM\remotes1e3c6f95612\fenguoerbian-RSAVS-8847f9c/DESCRIPTION' (591ms)
─  preparing 'RSAVS': (367ms)
✔  checking DESCRIPTION meta-information
─  cleaning src
   Warning in cleanup_pkg(pkgdir, Log) :
     unable to run 'make clean' in 'src'
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories (371ms)
─  building 'RSAVS_0.1.3.tar.gz'
   
'\\Mac\Home\Documents'
����Ϊ��ǰĿ¼������·������� CMD.EXE��
UNC ·������֧�֡�Ĭ��ֵ��Ϊ Windows Ŀ¼��
* installing *source* package 'RSAVS' ...
** using staged installation
** libs
Error in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  : 
  'make' not found
* removing 'C:/Rdownload/R-4.4.0/library/RSAVS'
警告信息:
In i.p(...) :
  安装程序包‘C:/Users/LIUYAH~1/AppData/Local/Temp/RtmpIhEufM/file1e3c58aa382e/RSAVS_0.1.3.tar.gz’时退出狀態的值不是0

**Comment by fenguoerbian** [comment]
Well, according to [Writing R extensions](https://mirrors.tuna.tsinghua.edu.cn/CRAN/doc/manuals/r-release/R-exts.html#OpenMP-support-1), support of OpenMP in MacOS coupled with clang is limited or even not exist. A workaround can be found at [this guide](https://mac.r-project.org/openmp/).

If this works, I suppose you will also have to download the package and adjust flags in [src/Makevars](https://github.com/fenguoerbian/RSAVS/blob/8847f9c997bedb84af3b440a02742c3e03b51485/src/Makevars) accordingly and then install the package from local path

**Comment by fenguoerbian** [comment]
If you want to install this package under Windows, you have to install the [rtools](https://mirrors.tuna.tsinghua.edu.cn/CRAN/) for installing source R packages on Windows.

**Comment by fenguoerbian** [comment]
Turns out there is also some old source code in this package which is not compatible with recent version of RcppEigen. I've updated the code and you can try again.

Though to be honest, the OpenMP support on Mac os part is still unchanged in this package.

**Comment by lyh199800** [comment]
OK thank you so much! I will try it again.

--------------原始邮件--------------
发件人："Chao&nbsp;Cheng ***@***.***&gt;;
发送时间：2024年5月25日(星期六) 下午4:48
收件人："fenguoerbian/RSAVS" ***@***.***&gt;;
抄送："lyh199800 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [fenguoerbian/RSAVS] Cannot install in R (Issue #3)
-----------------------------------

 

 
Turns out there is also some old source code in this package which is not compatible with recent version of RcppEigen. I've updated the code and you can try again.
 
Though to be honest, the OpenMP support on Mac os part is still unchanged in this package.

**Comment by fenguoerbian** [comment]
Close the issue since no further reply. Feel free to re-open it if you still need some help on this topic.
